export const userData = {
  "login": "BugReportOnWeb",
  "id": 96491001,
  "node_id": "U_kgDOBcBV-Q",
  "avatar_url": "https://avatars.githubusercontent.com/u/96491001?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/BugReportOnWeb",
  "html_url": "https://github.com/BugReportOnWeb",
  "followers_url": "https://api.github.com/users/BugReportOnWeb/followers",
  "following_url": "https://api.github.com/users/BugReportOnWeb/following{/other_user}",
  "gists_url": "https://api.github.com/users/BugReportOnWeb/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/BugReportOnWeb/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/BugReportOnWeb/subscriptions",
  "organizations_url": "https://api.github.com/users/BugReportOnWeb/orgs",
  "repos_url": "https://api.github.com/users/BugReportOnWeb/repos",
  "events_url": "https://api.github.com/users/BugReportOnWeb/events{/privacy}",
  "received_events_url": "https://api.github.com/users/BugReportOnWeb/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Dev",
  "company": null,
  "blog": "devkaul.vercel.app",
  "location": "HP, India",
  "email": null,
  "hireable": null,
  "bio": "Hobbyist dev",
  "twitter_username": null,
  "public_repos": 31,
  "public_gists": 0,
  "followers": 15,
  "following": 7,
  "created_at": "2021-12-21T16:51:30Z",
  "updated_at": "2024-01-12T11:40:17Z"
}
