version: "3"
services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    restart: unless-stopped
  client:
    build: ./client
    ports:
      - "8000:5173"
    depends_on:
      - server
    restart: unless-stopped
