version: "3"
services:
  db:
    image: postgres:14
    container_name: reponex-db
    env_file: ./server/.env
    ports:
      - "5432:5432"
    restart: unless-stopped
  server:
    container_name: reponex-server
    build: ./server
    environment:
      POSTGRES_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped
  client:
    container_name: reponex-client
    build: ./client
    ports:
      - "8000:5173"
    depends_on:
      - server
    restart: unless-stopped
